export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const CHANGE_ARTICLE_FILTER = "CHANGE_ARTICLE_FILTER"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS"
export const GET_SOCIALMEDIA_SUCCESS = "GET_SOCIALMEDIA_SUCCESS"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const SET_FILTER_RESULT_SUCCESS = "SET_FILTER_RESULT_SUCCESS"

